spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/test
    username: The10000HourRule
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml